# Generated by Django 3.1.3 on 2020-11-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='username',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
