# Generated by Django 3.1.3 on 2020-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingdetail_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('numticket', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cardnumber', models.IntegerField()),
            ],
        ),
    ]
